workflows:
  version: 2
  build:
    jobs:
      - build

version: 2
jobs:
  build:
    working_directory: ~/node-app
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint files
          command: yarn lint
 